### ISSUE TITLE
{Update}can add update + chromedriver

### ISSUE THREAD

**Issue by lolminerxmrig** [tarekrahman3/Google_Maps_Scraper#1]
Hi.
not download and start;

Google_Maps_Scraper-main\Google_Maps_Scraper-main>map_business_scrap.py
====== WebDriver manager ======
Current google-chrome version is 109.0.5414
Get LATEST chromedriver version for 109.0.5414 google-chrome
There is no [win32] chromedriver for browser  in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_win32.zip

**Comment by tarekrahman3** [comment]
latest source will not be released publicly, sorry :(
